name: Deploy

on:
  push:
    branches:
      - main

env:
  EKS_CLUSTER_NAME: tech-challenge
  AWS_REGION: us-east-1

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:

    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      env:
      run: |
        kubectl apply -f kubernetes/configmap/db-deployment-configmap.yaml
        kubectl apply -f kubernetes/secrets/postgres-secrets.yaml
        kubectl apply -f kubernetes/volume.yaml
        kubectl apply -f kubernetes/deployments/db-deployment.yaml
        kubectl apply -f kubernetes/services/db-service.yaml
        kubectl apply -f kubernetes/configmap/deployment-configmap.yaml
        kubectl apply -f kubernetes/secrets/challenge-secrets.yaml
        kubectl apply -f kubernetes/deployments/deployment.yaml
        kubectl apply -f kubernetes/services/service.yml
